CREATE DATABASE SpringBoot;

CREATE TABLE KHOA (
    ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    NAME NVARCHAR(50)
);

CREATE TABLE SINHVIEN (
    ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    NAME NVARCHAR(50),
    GENDER INT,
    BIRTHDAY DATE,
    KHOAID INT FOREIGN KEY REFERENCES KHOA(ID)
);

--ALTER TABLE KHOA ALTER COLUMN NAME NVARCHAR(50);

INSERT INTO KHOA (ID, NAME) VALUES (1, "Toán");
INSERT INTO KHOA (ID, NAME) VALUES (2, "Lý");
INSERT INTO KHOA (ID, NAME) VALUES (3, "Hóa");


INSERT INTO SINHVIEN (ID, NAME, GENDER, BIRTHDAY, KHOAID) VALUES (1, "Đỗ Hoàng Phương", 1, "1993-11-01", 1);
INSERT INTO SINHVIEN (ID, NAME, GENDER, BIRTHDAY, KHOAID) VALUES (2, "Châu Kiệt Luân", 1, "1990-01-01", 2);
INSERT INTO SINHVIEN (ID, NAME, GENDER, BIRTHDAY, KHOAID) VALUES (3, "Lý Hương Hương", 1, "1996-03-02", 3);
